name: Pull Request
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test_set: ["set_1", "set_2"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      ## Write for matrix outputs workaround 
      - uses: cloudposse/github-action-matrix-outputs-write@main
        id: out
        with:
          matrix-step-name: ${{ github.job }}
          matrix-key: ${{ matrix.test_set }}
          outputs: |-
            results_id: ${{ matrix.test_set }}-some-id
            ## Multiline string
            job_data: ${{ toJson(job) }}

  ## Read matrix outputs 
  read:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: cloudposse/github-action-matrix-outputs-read@main
        id: read
        with:
          matrix-step-name: build
    
      - name: Read resutls
        run: echo ${{ steps.read.outputs.result }}

    outputs:
      result: "${{ steps.read.outputs.result }}"