name: 'E2E'

on:
  workflow_dispatch:
    inputs:
      bstack_ios_app:
        description: 'Browserstack iOS app'
      bstack_android_app:
        description: 'Browserstack Android app'

jobs:
  build:
    strategy:
      matrix:
        include:
          - platform: android
          - platform: ios
    runs-on: ubuntu-latest
    env:
      BSTACK_APP_PROVIDED: ${{ (matrix.platform == 'android' && github.event.inputs.bstack_android_app == '') || (matrix.platform == 'ios' && github.event.inputs.bstack_ios_app == '') }}
    steps:
      - name: 🚀 Create build
        if: env.BSTACK_APP_PROVIDED == "false"
        run: |
          echo ${{ env.BSTACK_APP_PROVIDED }}
          echo "Create build for ${{ matrix.platform }}"


  test:
    needs: build
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: android
          - platform: ios
    runs-on: ubuntu-latest
    env:
      BSTACK_APP_PROVIDED: ${{ (matrix.platform == 'android' && github.event.inputs.bstack_android_app == '') || (matrix.platform == 'ios' && github.event.inputs.bstack_ios_app == '') }}
    steps:
      - name: Debug info
        run: echo ${{ env.BSTACK_APP_PROVIDED }}
      - name: Upload build to Browserstack
        if: env.BSTACK_APP_PROVIDED == "false"
        run: |
          echo ${{ env.BSTACK_APP_PROVIDED }}
          BROWSERSTACK_APP_URL="bs://sample-url-of-created-app-inside-workflow"
          echo "BROWSERSTACK_APP_URL=$BROWSERSTACK_APP_URL"
          echo "BROWSERSTACK_APP_URL=$BROWSERSTACK_APP_URL" >> $GITHUB_ENV

      - name: Run tests
        run: |
          if [ "${{ matrix.platform }}" == "android" ] && [ -n "${{ github.event.inputs.bstack_android_app }}" ]; then
            export BROWSERSTACK_APP_URL="${{ github.event.inputs.bstack_android_app}}"
          elif [ "${{ matrix.platform }}" == "ios" ] && [ -n "${{ github.event.inputs.bstack_ios_app }}" ]; then
            export BROWSERSTACK_APP_URL="${{ github.event.inputs.bstack_ios_app}}"
          else
            export BROWSERSTACK_APP_URL="${{ env.BROWSERSTACK_APP_URL }}"
          fi
          echo "Run tests for $BROWSERSTACK_APP_URL"