name: PR

on:
  pull_request:
    branches:
      - 'main'
    types:
      # update
      # - opened
      # - synchronize
      # - reopened
      - ready_for_review

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo hello world