name: PR

on:
  pull_request:
    branches:
      - 'main'
    types:
      - ready_for_review

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 5m